// portfolio/components/about.tsx
"use client"

import { motion } from "framer-motion"
import { Card, CardContent } from "@/components/ui/card"
import { MapPin } from "lucide-react"

export function About() {
  return (
    <section id="about" className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="max-w-3xl mx-auto"
        >
          <h2 className="text-3xl font-bold text-center mb-12">About Me</h2>

          <Card>
            <CardContent className="p-6">
              <div className="flex items-center mb-4">
                <div className="flex items-center text-muted-foreground">
                  <MapPin className="h-4 w-4 mr-2" />
                  <span>Thrissur, Kerala, India</span>
                </div>
              </div>

              <p className="mb-4">
                I'm a front-end developer with proven experience at Cakap and Qburst in helping them create and maintain
                a better code base for reusability. Passionate about learning and development with a desire to apply
                skills.
              </p>

              <p className="mb-4">
                With over 7 years of experience in Angular and 5 years in React, I've developed a strong foundation in
                building responsive, user-friendly web applications that deliver exceptional user experiences.
              </p>

              <p>
                I'm eager to tackle more complex problems and continue to find ways to maximize user efficiency. My
                expertise includes developing dashboards, RTC interfaces for video and audio conversations, and
                real-time chat services for interaction between users.
              </p>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </section>
  )
}

// portfolio/src/views/About.vue
<script setup lang="ts">
import { MapPin } from 'lucide-vue-next'
import Card from '@/components/ui/Card.vue'
import CardContent from '@/components/ui/CardContent.vue'
</script>

<template>
  <div class="pt-24">
    <section id="about" class="section-alt">
      <div class="container mx-auto px-4">
        <div
          v-motion
          :initial="{ opacity: 0, y: 12 }"
          :enter="{ opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } }"
          class="max-w-3xl mx-auto"
        >
          <h2 class="section-heading">About Me</h2>

          <Card class="overflow-hidden transition-shadow duration-300 hover:shadow-md">
            <CardContent class="p-6 md:p-8">
              <div class="flex items-center gap-2 text-muted-foreground mb-6">
                <MapPin class="h-4 w-4 shrink-0" />
                <span>Thrissur, Kerala, India</span>
              </div>

              <p class="mb-4 leading-relaxed text-muted-foreground/90">
                Senior Frontend Engineer with 8+ years of experience building high-performance, scalable web applications
                across education, real-time communication, and data-driven platforms. Strong expertise in React, Next.js,
                and Angular, with focus on component-driven architecture, performance optimization, accessibility
                (WCAG), SEO, and design systems.
              </p>

              <p class="mb-4 leading-relaxed text-muted-foreground/90">
                I own features end-to-end, mentor engineers, and collaborate with product, design, and backend teams to
                deliver production-grade user experiences at scale. My expertise includes dashboards, WebRTC interfaces
                for video and audio, and real-time chat services.
              </p>

              <p class="leading-relaxed text-muted-foreground/90">
                React-first mindset with a strong Angular background; focused on performance, scalability, SEO, and
                proven ability to work in remote, cross-functional teams.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  </div>
</template>
