// portfolio/src/components/Contact.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Mail, MapPin, Phone } from 'lucide-vue-next'
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardTitle from '@/components/ui/CardTitle.vue'
import CardDescription from '@/components/ui/CardDescription.vue'
import CardContent from '@/components/ui/CardContent.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Textarea from '@/components/ui/Textarea.vue'
import { useToast } from '@/composables/useToast'

const formData = ref({
  name: '',
  email: '',
  subject: '',
  message: '',
})
const isSubmitting = ref(false)
const { toast } = useToast()

function handleSubmit(e: Event) {
  e.preventDefault()
  isSubmitting.value = true

  setTimeout(() => {
    toast({
      title: 'Message sent!',
      description: "Thank you for your message. I'll get back to you soon.",
    })
    formData.value = { name: '', email: '', subject: '', message: '' }
    isSubmitting.value = false
  }, 1500)
}
</script>

<template>
  <section id="contact" class="py-20 bg-muted/30">
    <div class="container mx-auto px-4">
      <div
        v-motion
        :initial="{ opacity: 0, y: 20 }"
        :enter="{ opacity: 1, y: 0, transition: { duration: 500 } }"
      >
        <h2 class="text-3xl font-bold text-center mb-12">Get In Touch</h2>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          <Card>
            <CardHeader>
              <CardTitle>Contact Information</CardTitle>
              <CardDescription>Feel free to reach out to me through any of these channels.</CardDescription>
            </CardHeader>
            <CardContent class="space-y-4">
              <div class="flex items-center">
                <MapPin class="h-5 w-5 mr-3 text-primary" />
                <div>
                  <p class="font-medium">Location</p>
                  <p class="text-muted-foreground">Thrissur, Kerala, India</p>
                </div>
              </div>

              <div class="flex items-center">
                <Mail class="h-5 w-5 mr-3 text-primary" />
                <div>
                  <p class="font-medium">Email</p>
                  <a
                    href="mailto:akhiljohnson2000@gmail.com"
                    class="text-muted-foreground hover:text-primary transition-colors"
                  >
                    akhiljohnson2000@gmail.com
                  </a>
                </div>
              </div>

              <div class="flex items-center">
                <Phone class="h-5 w-5 mr-3 text-primary" />
                <div>
                  <p class="font-medium">Phone</p>
                  <a href="tel:+919809194911" class="text-muted-foreground hover:text-primary transition-colors">
                    +91 9809194911
                  </a>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Send a Message</CardTitle>
              <CardDescription>Fill out the form below and I'll get back to you as soon as possible.</CardDescription>
            </CardHeader>
            <CardContent>
              <form class="space-y-4" @submit="handleSubmit">
                <div>
                  <Input
                    v-model="formData.name"
                    placeholder="Your Name"
                    name="name"
                    required
                  />
                </div>
                <div>
                  <Input
                    v-model="formData.email"
                    type="email"
                    placeholder="Your Email"
                    name="email"
                    required
                  />
                </div>
                <div>
                  <Input
                    v-model="formData.subject"
                    placeholder="Subject"
                    name="subject"
                    required
                  />
                </div>
                <div>
                  <Textarea
                    v-model="formData.message"
                    placeholder="Your Message"
                    name="message"
                    :rows="5"
                    required
                  />
                </div>
                <Button type="submit" class="w-full" :disabled="isSubmitting">
                  {{ isSubmitting ? 'Sending...' : 'Send Message' }}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  </section>
</template>

// portfolio/components/contact.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { motion } from "framer-motion"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Mail, MapPin, Phone } from "lucide-react"
import { toast } from "@/components/ui/use-toast"

export function Contact() {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    subject: "",
    message: "",
  })
  const [isSubmitting, setIsSubmitting] = useState(false)

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target
    setFormData((prev) => ({ ...prev, [name]: value }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)

    // Simulate form submission
    setTimeout(() => {
      toast({
        title: "Message sent!",
        description: "Thank you for your message. I'll get back to you soon.",
      })
      setFormData({
        name: "",
        email: "",
        subject: "",
        message: "",
      })
      setIsSubmitting(false)
    }, 1500)
  }

  return (
    <section id="contact" className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl font-bold text-center mb-12">Get In Touch</h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
            <Card>
              <CardHeader>
                <CardTitle>Contact Information</CardTitle>
                <CardDescription>Feel free to reach out to me through any of these channels.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center">
                  <MapPin className="h-5 w-5 mr-3 text-primary" />
                  <div>
                    <p className="font-medium">Location</p>
                    <p className="text-muted-foreground">Thrissur, Kerala, India</p>
                  </div>
                </div>

                <div className="flex items-center">
                  <Mail className="h-5 w-5 mr-3 text-primary" />
                  <div>
                    <p className="font-medium">Email</p>
                    <a
                      href="mailto:akhiljohnson2000@gmail.com"
                      className="text-muted-foreground hover:text-primary transition-colors"
                    >
                      akhiljohnson2000@gmail.com
                    </a>
                  </div>
                </div>

                <div className="flex items-center">
                  <Phone className="h-5 w-5 mr-3 text-primary" />
                  <div>
                    <p className="font-medium">Phone</p>
                    <a href="tel:+919809194911" className="text-muted-foreground hover:text-primary transition-colors">
                      +91 9809194911
                    </a>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Send a Message</CardTitle>
                <CardDescription>Fill out the form below and I'll get back to you as soon as possible.</CardDescription>
              </CardHeader>
              <CardContent>
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div>
                    <Input placeholder="Your Name" name="name" value={formData.name} onChange={handleChange} required />
                  </div>
                  <div>
                    <Input
                      type="email"
                      placeholder="Your Email"
                      name="email"
                      value={formData.email}
                      onChange={handleChange}
                      required
                    />
                  </div>
                  <div>
                    <Input
                      placeholder="Subject"
                      name="subject"
                      value={formData.subject}
                      onChange={handleChange}
                      required
                    />
                  </div>
                  <div>
                    <Textarea
                      placeholder="Your Message"
                      name="message"
                      value={formData.message}
                      onChange={handleChange}
                      rows={5}
                      required
                    />
                  </div>
                  <Button type="submit" className="w-full" disabled={isSubmitting}>
                    {isSubmitting ? "Sending..." : "Send Message"}
                  </Button>
                </form>
              </CardContent>
            </Card>
          </div>
        </motion.div>
      </div>
    </section>
  )
}
