// portfolio/src/views/Projects.vue
<script setup lang="ts">
import Card from '@/components/ui/Card.vue'
import CardHeader from '@/components/ui/CardHeader.vue'
import CardContent from '@/components/ui/CardContent.vue'
import CardFooter from '@/components/ui/CardFooter.vue'
import CardTitle from '@/components/ui/CardTitle.vue'
import CardDescription from '@/components/ui/CardDescription.vue'
import Badge from '@/components/ui/Badge.vue'
import Button from '@/components/ui/Button.vue'
import { ref } from 'vue'
import { RouterLink } from 'vue-router'
import { ExternalLink, Github } from 'lucide-vue-next'

function isInternalLink(link?: string) {
  return link?.startsWith('/')
}

const activeTab = ref<'career' | 'personal'>('career')

interface Project {
  title: string
  description: string
  image: string
  technologies: string[]
  link?: string
  github?: string
  company?: string
}

const careerProjects: Project[] = [
  {
    title: 'KidKiosk',
    description:
      'A kids management application for parents built with Angular and Cordova, facilitating improved student data management and communication between parents and daycare.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['Angular', 'Cordova', 'TypeScript', 'SCSS'],
    link: 'https://www.kidkiosk.com',
    company: 'QBurst',
  },
  {
    title: 'Cakap Learning Platform',
    description:
      'Developed dashboards for teachers and students for booking classes, coordinating mark sheets, and tracking activities. Implemented RTC interface for video/audio conversations.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['Angular', 'React', 'TypeScript', 'Twilio.js', 'Agora'],
    link: 'https://cakap.com',
    company: 'Cakap',
  },
  {
    title: 'Ecosystm Data Visualization',
    description:
      'Developed the front end of a data visualization platform in Angular with highcharts.js and d3.js libraries. Reduced page load time by 30% and improved user engagement by 20%.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['Angular', 'Highcharts', 'd3.js', 'TypeScript'],
    link: 'https://ecosystm.io/',
    company: 'Perfomatix',
  },
  {
    title: 'Trading Application',
    description:
      'Developed an internal trading application for automating trading strategies with real-time data visualization and analytics.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['Angular', 'React', 'd3.js', 'MongoDB'],
    company: 'QBurst',
  },
]

const personalProjects: Project[] = [
  {
    title: 'Portfolio Website',
    description:
      'A modern, responsive portfolio website built with Vue.js and Tailwind CSS to showcase my skills and projects.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['Vue.js', 'Vite', 'Tailwind CSS', 'TypeScript'],
    github: 'https://github.com/akhiljohnson2000/portfolio',
    link: 'https://akhiljohnson2000.github.io',
  },
  {
    title: 'Weather Dashboard',
    description:
      'A weather dashboard application that provides real-time weather information for any location using the OpenWeatherMap API.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'OpenWeatherMap API'],
    github: 'https://github.com/akhiljohnson2000/weather-dashboard',
  },
  {
    title: 'Task Management App',
    description:
      'A full-stack task management application with authentication, task creation, and organization features.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['Angular', 'Node.js', 'Express', 'MongoDB'],
    github: 'https://github.com/akhiljohnson2000/task-manager',
  },
  {
    title: 'E-commerce UI Components',
    description:
      'A collection of reusable UI components for e-commerce applications, including product cards, shopping carts, and checkout forms.',
    image: '/placeholder.svg?height=200&width=400',
    technologies: ['React', 'Storybook', 'Styled Components'],
    github: 'https://github.com/akhiljohnson2000/ecommerce-components',
  },
]
</script>

<template>
  <div class="pt-24">
    <section id="projects" class="section-alt">
      <div class="container mx-auto px-4">
      <div
        v-motion
        :initial="{ opacity: 0, y: 12 }"
        :enter="{ opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } }"
      >
        <h2 class="section-heading">Projects</h2>

        <div class="w-full">
          <div class="grid w-full max-w-md mx-auto grid-cols-2 mb-12 rounded-md bg-muted p-1 text-muted-foreground">
            <button
              type="button"
              class="inline-flex h-10 items-center justify-center rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
              :class="activeTab === 'career' ? 'bg-background text-foreground shadow-sm' : 'hover:text-foreground'"
              @click="activeTab = 'career'"
            >
              Career Projects
            </button>
            <button
              type="button"
              class="inline-flex h-10 items-center justify-center rounded-sm px-3 py-1.5 text-sm font-medium ring-offset-background transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50"
              :class="activeTab === 'personal' ? 'bg-background text-foreground shadow-sm' : 'hover:text-foreground'"
              @click="activeTab = 'personal'"
            >
              Personal Projects
            </button>
          </div>

          <div v-show="activeTab === 'career'" class="mt-2">
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <div
                v-for="(project, index) in careerProjects"
                :key="index"
                v-motion
                :initial="{ opacity: 0, y: 20 }"
                :enter="{ opacity: 1, y: 0, transition: { duration: 0.32, delay: index * 60, ease: 'easeOut' } }"
              >
              <Card class="h-full flex flex-col transition-shadow duration-300 hover:shadow-md">
                  <CardHeader>
                    <div class="flex justify-between items-start">
                      <div>
                        <CardTitle>{{ project.title }}</CardTitle>
                        <CardDescription v-if="project.company">{{ project.company }}</CardDescription>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent class="flex-grow">
                    <p class="text-muted-foreground mb-4">{{ project.description }}</p>
                    <div class="flex flex-wrap gap-2">
                      <Badge v-for="(tech, i) in project.technologies" :key="i" variant="secondary">
                        {{ tech }}
                      </Badge>
                    </div>
                  </CardContent>
                  <CardFooter class="flex gap-2">
                    <Button v-if="project.github" variant="outline" size="sm" as="a" :href="project.github" target="_blank" rel="noopener noreferrer">
                      <Github class="h-4 w-4 mr-2" />
                      GitHub
                    </Button>
                    <RouterLink v-if="project.link && isInternalLink(project.link)" :to="project.link" class="inline-flex items-center justify-center h-9 rounded-md px-3 text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90">
                      <ExternalLink class="h-4 w-4 mr-2" />
                      Visit
                    </RouterLink>
                    <Button v-else-if="project.link" size="sm" as="a" :href="project.link" target="_blank" rel="noopener noreferrer">
                      <ExternalLink class="h-4 w-4 mr-2" />
                      Visit
                    </Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>

          <div v-show="activeTab === 'personal'" class="mt-2">
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <div
                v-for="(project, index) in personalProjects"
                :key="index"
                v-motion
                :initial="{ opacity: 0, y: 20 }"
                :enter="{ opacity: 1, y: 0, transition: { duration: 0.32, delay: index * 60, ease: 'easeOut' } }"
              >
                <Card class="h-full flex flex-col transition-shadow duration-300 hover:shadow-md">
                  <CardHeader>
                    <div class="flex justify-between items-start">
                      <div>
                        <CardTitle>{{ project.title }}</CardTitle>
                        <CardDescription v-if="project.company">{{ project.company }}</CardDescription>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent class="flex-grow">
                    <p class="text-muted-foreground mb-4">{{ project.description }}</p>
                    <div class="flex flex-wrap gap-2">
                      <Badge v-for="(tech, i) in project.technologies" :key="i" variant="secondary">
                        {{ tech }}
                      </Badge>
                    </div>
                  </CardContent>
                  <CardFooter class="flex gap-2">
                    <Button v-if="project.github" variant="outline" size="sm" as="a" :href="project.github" target="_blank" rel="noopener noreferrer">
                      <Github class="h-4 w-4 mr-2" />
                      GitHub
                    </Button>
                    <RouterLink v-if="project.link && isInternalLink(project.link)" :to="project.link" class="inline-flex items-center justify-center h-9 rounded-md px-3 text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90">
                      <ExternalLink class="h-4 w-4 mr-2" />
                      Visit
                    </RouterLink>
                    <Button v-else-if="project.link" size="sm" as="a" :href="project.link" target="_blank" rel="noopener noreferrer">
                      <ExternalLink class="h-4 w-4 mr-2" />
                      Visit
                    </Button>
                  </CardFooter>
                </Card>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </section>
  </div>
</template>

// portfolio/components/projects.tsx
"use client"

import { motion } from "framer-motion"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ExternalLink, Github } from "lucide-react"

// Career projects based on the resume
const careerProjects = [
  {
    title: "KidKiosk",
    description:
      "A kids management application for parents built with Angular and Cordova, facilitating improved student data management and communication between parents and daycare.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["Angular", "Cordova", "TypeScript", "SCSS"],
    link: "https://www.kidkiosk.com",
    company: "QBurst",
  },
  {
    title: "Cakap Learning Platform",
    description:
      "Developed dashboards for teachers and students for booking classes, coordinating mark sheets, and tracking activities. Implemented RTC interface for video/audio conversations.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["Angular", "React", "TypeScript", "Twilio.js", "Agora"],
    link: "https://cakap.com",
    company: "Cakap",
  },
  {
    title: "Ecosystm Data Visualization",
    description:
      "Developed the front end of a data visualization platform in Angular with highcharts.js and d3.js libraries. Reduced page load time by 30% and improved user engagement by 20%.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["Angular", "Highcharts", "d3.js", "TypeScript"],
    link: "https://ecosystm.io/",
    company: "Perfomatix",
  },
  {
    title: "Trading Application",
    description:
      "Developed an internal trading application for automating trading strategies with real-time data visualization and analytics.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["Angular", "React", "d3.js", "MongoDB"],
    company: "QBurst",
  },
]

// Personal projects (example projects since none were specified)
const personalProjects = [
  {
    title: "Portfolio Website",
    description:
      "A modern, responsive portfolio website built with Next.js and Tailwind CSS to showcase my skills and projects.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["Next.js", "React", "Tailwind CSS", "TypeScript"],
    github: "https://github.com/akhiljohnson2000/portfolio",
    link: "https://akhiljohnson2000.github.io",
  },
  {
    title: "Weather Dashboard",
    description:
      "A weather dashboard application that provides real-time weather information for any location using the OpenWeatherMap API.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["React", "TypeScript", "Tailwind CSS", "OpenWeatherMap API"],
    github: "https://github.com/akhiljohnson2000/weather-dashboard",
  },
  {
    title: "Task Management App",
    description:
      "A full-stack task management application with authentication, task creation, and organization features.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["Angular", "Node.js", "Express", "MongoDB"],
    github: "https://github.com/akhiljohnson2000/task-manager",
  },
  {
    title: "E-commerce UI Components",
    description:
      "A collection of reusable UI components for e-commerce applications, including product cards, shopping carts, and checkout forms.",
    image: "/placeholder.svg?height=200&width=400",
    technologies: ["React", "Storybook", "Styled Components"],
    github: "https://github.com/akhiljohnson2000/ecommerce-components",
  },
]

export function Projects() {
  return (
    <section id="projects" className="py-20 bg-muted/30">
      <div className="container mx-auto px-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl font-bold text-center mb-12">Projects</h2>

          <Tabs defaultValue="career" className="w-full">
            <TabsList className="grid w-full max-w-md mx-auto grid-cols-2 mb-12">
              <TabsTrigger value="career">Career Projects</TabsTrigger>
              <TabsTrigger value="personal">Personal Projects</TabsTrigger>
            </TabsList>

            <TabsContent value="career">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {careerProjects.map((project, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                  >
                    <ProjectCard project={project} />
                  </motion.div>
                ))}
              </div>
            </TabsContent>

            <TabsContent value="personal">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {personalProjects.map((project, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5, delay: index * 0.1 }}
                    viewport={{ once: true }}
                  >
                    <ProjectCard project={project} />
                  </motion.div>
                ))}
              </div>
            </TabsContent>
          </Tabs>
        </motion.div>
      </div>
    </section>
  )
}

function ProjectCard({ project }: { project: any }) {
  return (
    <Card className="h-full flex flex-col">
      <div className="aspect-video w-full overflow-hidden">
        <img
          src={project.image || "/placeholder.svg"}
          alt={project.title}
          className="w-full h-full object-cover transition-transform duration-300 hover:scale-105"
        />
      </div>
      <CardHeader>
        <div className="flex justify-between items-start">
          <div>
            <CardTitle>{project.title}</CardTitle>
            {project.company && <CardDescription>{project.company}</CardDescription>}
          </div>
        </div>
      </CardHeader>
      <CardContent className="flex-grow">
        <p className="text-muted-foreground mb-4">{project.description}</p>
        <div className="flex flex-wrap gap-2">
          {project.technologies.map((tech: string, i: number) => (
            <Badge key={i} variant="secondary">
              {tech}
            </Badge>
          ))}
        </div>
      </CardContent>
      <CardFooter className="flex gap-2">
        {project.github && (
          <Button variant="outline" size="sm" asChild>
            <a href={project.github} target="_blank" rel="noopener noreferrer">
              <Github className="h-4 w-4 mr-2" />
              GitHub
            </a>
          </Button>
        )}
        {project.link && (
          <Button size="sm" asChild>
            <a href={project.link} target="_blank" rel="noopener noreferrer">
              <ExternalLink className="h-4 w-4 mr-2" />
              Visit
            </a>
          </Button>
        )}
      </CardFooter>
    </Card>
  )
}
